### ISSUE TITLE
CLI flags

### ISSUE THREAD

**Issue by ArxdSilva** [ArxdSilva/XML-Comp#15]
It would be nice to have some flags like:
- '-v' for version
- '-fd' for only folder verification 
- '-fl' for file verifications

**Comment by shubhodeep9** [comment]
Yes it can be done.
@ArxdSilva can you provide me with few details,
- Current `version` of the application
- Functions for file verification, as I am not able to find it.

**Comment by alkhatib** [comment]
The PR above sets up the flag usage for the CLI
I added -original and -translate flags
And a help message that gets printed out if requested by the -h flag, or when the required flags are missing.

**Comment by ArxdSilva** [comment]
@shubhodeep9, I just added the const Version today, about the functions It's in v0.0.3 milestones and will be added soon.

**Comment by shubhodeep9** [comment]
@ArxdSilva Okay then, I'll make a PR soon, on top of CLI merge.
