### ISSUE TITLE
Turn this project CLI viable

### ISSUE THREAD

**Issue by ArxdSilva** [ArxdSilva/XML-Comp#2]
To make this viable we need the implementation of: 
```shell
$ xml-comp PathA PathB
```

**Comment by shubhodeep9** [comment]
Hi @ArxdSilva, can you please mention requirements in the description of the issue or as a separate comment.
Thank you

**Comment by ArxdSilva** [comment]
@shubhodeep9  updated, hope this helps you enought

**Comment by shubhodeep9** [comment]
@ArxdSilva yup, thanks for notifying.

**Comment by shubhodeep9** [comment]
@ArxdSilva regarding **enhancement**, CLI installation you need to create an account on the version controls of each OS, for eg, launchpad.net for linux. So I'd suggest, make installation through `go get https://github.com/ArxdSilva/XML-Comp`, this will infact build the file and make it available for use ie `$ xml-comp PathA PathB`. Let me know your views.

**Comment by ArxdSilva** [comment]
I agree, but I believe that It needs to be more general, because It will be used by people that only wants to translate and may know nothing about programming (my initial idea). 

If we only use `go get https://github.com/ArxdSilva/XML-Comp` only people that knows what Go and that has It installed will use. I'll separate the installer & CLI in different issues, because the Installer might be something that doest not depend on CLI but can be done in It.

**Comment by shubhodeep9** [comment]
@ArxdSilva yup I totally agree to your point. So separate the issues and I'll start working on the CLI build.

**Comment by ArxdSilva** [comment]
Done (:
